#!/bin/bash

# Name: music_image_scraper
# Description: Script to download images related to music using the ImageScraperSuite.
# License: LGPL
# GitHub: https://github.com/raven2cz/ImageScraperSuite

VERSION="1.0.0"
HELP_MESSAGE="Usage: $0 [options] <song_name> <artist_name> [album_name]
Options:
  -h, --help        Display this help message and exit.
  -v, --version     Display script version and exit.

Arguments:
  song_name         Name of the song.
  artist_name       Name of the artist.
  album_name        Name of the album (optional)."

# Function to display help message
function show_help {
  echo "$HELP_MESSAGE"
}

# Function to display version
function show_version {
  echo "music_image_scraper version $VERSION"
}

# Parse options
while [[ "$#" -gt 0 ]]; do
  case $1 in
    -h|--help) show_help; exit 0 ;;
    -v|--version) show_version; exit 0 ;;
    *) break ;;
  esac
  shift
done

# Check for mandatory arguments
if [ "$#" -lt 2 ]; then
  echo "Error: Missing required arguments."
  echo ""
  show_help
  exit 1
fi

SONG_NAME=$1
ARTIST_NAME=$2
ALBUM_NAME=${3:-''}

# Run scripts
node generateImageKeywordsFromSong.js "$SONG_NAME" "$ARTIST_NAME" "$ALBUM_NAME" &&
node scrapeImages.js &&
node removeDuplicateAndCorruptedImages.js

echo "Process completed."
